# Generated by Django 2.1.7 on 2019-04-25 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hit_points', models.PositiveSmallIntegerField(default=100)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('atk_points', models.PositiveSmallIntegerField(default=1)),
                ('def_points', models.PositiveSmallIntegerField(default=1)),
                ('guild', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='halloffame.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('can_fight_with', models.ManyToManyField(related_name='_race_can_fight_with_+', to='halloffame.Race')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halloffame.Race'),
        ),
    ]
